### ISSUE TITLE
Merge back

### ISSUE THREAD

**Issue by NITEMAN** [chriskuchin/terraform-provider-hiera5#5]
Hi, our apologies for not replying issues in a timely manner, we were on a work peak for months.

We will try to merge back some of your work and publish an official release to the registry ASAP

**Comment by chriskuchin** [comment]
Sounds  good Happy to help anyway I can.

**Comment by NITEMAN** [comment]
WIP: https://gitlab.com/sbitio/terraform-provider-hiera5/-/merge_requests/11

**Comment by NITEMAN** [comment]
Published: https://registry.terraform.io/providers/sbitio/hiera5/latest

Your contributions will be very welcomed on original project on GitLab
